### ISSUE TITLE
[경기도] 제안 작성 페이지 수정 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#100]
게시판 타입 '제안'의 입력 필드를 공모 형식으로 수정이 필요합니다. (수정 예정)

1. ~~공모 유형 (2가지)~~
    ~~- 공모 유형: 삼삼오오/ 정책상상~~
    ~~- 제목 상단에 라디오 버튼으로 공모 유형 선택~~
    ~~- 선택한 유형에 따라 작성 입력필드 노출~~
2. 유형에 따른 작성필드 
     - @partisoy 확정되면 유형별로 정리해주세요.
3. ~~글 등록 시 게시글에 공모 유형 태그 자동 추가~~

**Comment by anne-parti** [comment]
@partisoy 회의록 내용 확인하다 아래 내용을 봤는데요. 
> 삼삼오오와 정책상상은 게시판을 분리하여 운영

회의록에 따르면 1번 공모 유형 구분은 별도로 작업 진행하지 않아도 될까요?

**Comment by partisoy** [comment]
@anne-parti 아이고 제가 수정해서 말씀드리려고 했는데, 벌써 보셨군요! 네네, 1번은 진행하지 않으셔도 돼요. 나눠서 게시판을 운영하기로 했어요. 다만, 정책상상과 삼삼오오 입력 항목은 여전히 달라서, 두 게시판의 필드 양식은 다르게 적용되어야 합니다. 3번은 사업계획서제출게시판이나 모임/후기 게시판에서 필요할 수도 있어요. 월요일 회의 때 좀 더 자세히 설명드릴게요.

**Comment by anne-parti** [comment]
https://github.com/parti-coop/parti-mx-spa/issues/124 에 새로 작성해서 이슈 닫을게요.
