### ISSUE TITLE
[녹전연] og이미지, 파비콘

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#104]
og이미지, 파비콘 전달드립니다. @anne-parti @iamswain25 

커버 이미지는 작업된는대로 보내주시거나, 녹전연에서 직접 적용하기로 했습니다.

[og 이미지](https://drive.google.com/file/d/1x3iYD7tYJRoHkcjaudoi3caQe-5N27-k/view?usp=sharing), [파비콘](https://drive.google.com/file/d/15pPEDT5BjwFqMAmt-CygaSEXub6mwiUR/view?usp=sharing)

**Comment by anne-parti** [comment]
확인 완료했습니다.
