### ISSUE TITLE
[녹전연] 작성 페이지 수정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#108]
@jay-parti 아래 내용 확인해주시면 제나님께 작업 요청드리겠습니다. 

1. 필수, 선택 입력항목은 현재 플랫폼에 요청하신대로 적용되어 있는 것으로 보이는데요. 다시 한 번 확인 부탁드립니다. 

2. 2가지 중 한가지만 입력하도록 제안했을 때, 고정태그 미입력 시 상단에서 태그 선택해서 보는 사용자가 확인하지 못하는 글이 발생할 수 있을 것 같은데요. 그래서 말씀하신 것 처럼 주제 선택 필수 + 기타 태그 추가로 진행하면 좋겠습니다. 
        
3. 해시태그 관련 사항인데요. 
    - 주제 선택에 `기타`를 추가하면 아래 전달해주신 가이드 문구랑은 내용이 다른데요. 
        - `주제 선택에서 '기타'를 선택한 경우 주제를 직접 입력해주세요.`의 뉘앙스로 문구를 변경하는 것이 좋아보입니다. 정확한 문구는 제안해주세요. 
    - 말씀해주신 내용은 주소 하단 예)처럼 입력 폼 하단에 보여주는게 좋겠습니다. (플레이스 홀더는 그대로 유지)
        - <img width="945" alt="스크린샷 2021-02-15 오후 6 41 00" src="https://user-images.githubusercontent.com/55128558/107929728-693c6580-6fbd-11eb-9fbd-cd526ed5ca1b.png">

4. 모임
    - 입력 영역 레이블을 모임 장소(또는 화상회의 링크) 라고 작성했는데 `화상회의 링크`로 수정해야할까요?
    - 모임장소와 주소 둘 다 선택사항으로 놓는게 좋을 것 같은데요. 
        - 화상회의로 진행하는 경우, 글 작성 시 회의 링크가 정해지지 않았을 수도 있고요 링크를 비공개로 공유하는 경우가 있어 장소(링크) 영역은 입력을 강제하지 않는게 좋습니다. 
        - 주소 관련해서도 입력할 주소가 없는 경우가 발생할 수 있기 때문에 선택사항으로 두는게 어떨까 싶습니다. 

5. 지도
    각각 아래와 같이 정리하는게 좋을 것 같은데 확인 부탁드려요. (이미지 참고)
    <img width="934" alt="스크린샷 2021-02-15 오후 6 53 42" src="https://user-images.githubusercontent.com/55128558/107931098-2e3b3180-6fbf-11eb-93ca-dd213387a3f9.png">
    - 입력 레이블: 주소를 입력하세요
    - 플레이스 홀더: 예) 서울시특별시 서대문구 남가좌1동 서대문사회적경제마을센터
    - 가이드 문구: 주소 입력 시 게시판 지도에 위치정보가 표시됩니다.

참고 https://github.com/parti-coop/parti-mx-spa/issues/92
> 게시판별 입력필드 필수/선택 입력사항 전달드립니다. @anne-parti
> 
> **공론장**
> 
> * 제목 / 제안 배경 / 제안 종료 방법 / 제안 내용 : 필수
> * 주제 선택 / 해시태그 : 선택
> * 주소 : 선택
> 
> **모임**
> 
> * 모임명 / 일시 / 모집인원 / 신청마감일 / 내용 : 필수
> * 주제 선택 / 해시태그 : 선택 (*공론장과 동일)
> * 화상회의 링크 / 주소 : 선택
> 
> **도서관**
> 
> * 제목 / 내용 : 필수
> * 주제 선택 / 해시태그 : 선택 (*공론장과 동일)
> * 주소 : 선택
> 
> **문의**
> **공론장**
> 
> * 주제 선택과 해시태그 둘 중 하나를 필수가 가능할지 문의주셨습니다. 혹시 어렵다면 두 가지 모두 선택사항으로 하면 좋을 것 같다고 하셨는데요. / _주제선택을 필수로 하고, 고정태그에 '기타'를 추가하면 어떨까 싶습니다._
> * 해시태그 입력 전 보이는 문구를 다음과 같이 수정 요청주셨습니다. 모바일로 봤을 때 텍스트가 길지 않을까 싶긴한데 가능할까요?
>   ![image](https://user-images.githubusercontent.com/65703242/107907355-d7216680-6f96-11eb-8e42-4ec6f992412c.png)
>   _제안하고자 하는 내용의 주제를 기존 태그에서 선택할 수 없을 경우 추가해 주세요(단어 입력후 엔터를 눌러 추가하세요)_
> 
> **모임**
> 
> * 워딩은 ‘화상회의 링크'로 요청주셨습니다.
> * 화상회의 링크와 주소의 경우에도 둘 중 하나 필수가 가능할까요? 안된다면 두 개 다 선택으로 남기면 좋을 것 같습니다.

**Comment by jay-parti** [comment]
1. 넵 확인했습니다.
2. 넵. 주제 선택 필수 + 기타 태그추가로 요청드려요.
3. 안나님이 말씀해주신 내용 좋습니다. 그런데 이 부분은 녹전연에서 문구를 제시해주셨던게 있어서요. 다시 확인하고 문구 전달드리겠습니다.
4.  지금 적용된대로 (모임장소 또는 화상회의 링크)가 좋을 것 같습니다.  그리고 모임장소, 주소 모두 선택사항 좋습니다. 
5. 정리해주신 내용으로 배치하는게 주소 기입시 안내가 잘 될 것 같습니다.

3번 외에는 먼저 작업해주셔도 좋지 않을까 싶습니다. 정리 감사합니다 @anne-parti

**Comment by jay-parti** [comment]
3번 문구는 _주제 선택에서 ‘기타’를 선택한 경우 자세한 주제를 추가해주세요_ 로 요청드립니다. @anne-parti

**Comment by anne-parti** [comment]
@jenna1k 해시태그 입력폼 하단 가이드 문구 마지막에 온점(.)을 추가해주세요.
    - `주제 선택에서 ‘기타’를 선택한 경우 자세한 주제를 추가해주세요.`

@jay-parti 플랫폼에서 구현된 내용 확인 부탁드립니다.

**Comment by jay-parti** [comment]
내용 확인했고, 수정사항 말씀드립니다. @anne-parti 

1. 모임 : 모집인원 필수항목으로 수정 부탁드려요. 기본값이 10명으로 뜨는데요. 0명으로 조정할 수 있을까요? 시간이 오래걸린다면 건너뛰어도 좋을 것 같습니다.
2. 경고메시지 뜨기 전에는 '주제선택'이 필수항목처럼 안보여서요. 다른 항목들처럼 '주제선택*' 이런 식으로 표시할 수 있을까요?  
3. 공론장 : 입력필드 최하단 '제출하기' 버튼을 '제안하기'로 수정 부탁드립니다.
![image](https://user-images.githubusercontent.com/65703242/108034899-8df61300-7079-11eb-8669-d80bfd25b707.png)

**Comment by jenna1k** [comment]
수정사항 반영했습니다


> 내용 확인했고, 수정사항 말씀드립니다. @anne-parti
> 
> 1. 모임 : 모집인원 필수항목으로 수정 부탁드려요. 기본값이 10명으로 뜨는데요. 0명으로 조정할 수 있을까요? 시간이 오래걸린다면 건너뛰어도 좋을 것 같습니다.
> 2. 경고메시지 뜨기 전에는 '주제선택'이 필수항목처럼 안보여서요. 다른 항목들처럼 '주제선택*' 이런 식으로 표시할 수 있을까요?
> 3. 공론장 : 입력필드 최하단 '제출하기' 버튼을 '제안하기'로 수정 부탁드립니다.
>    ![image](https://user-images.githubusercontent.com/65703242/108034899-8df61300-7079-11eb-8669-d80bfd25b707.png)

**Comment by anne-parti** [comment]
수정 내용 확인했습니다. @jay-parti 님도 확인 부탁드려요.

**Comment by jay-parti** [comment]
넵 수정사항 확인했습니다.
