### ISSUE TITLE
[녹전연] 메인 이미지 (PC 버전) 수정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#109]
녹전연에서 전달받으면 수정 예정입니다. @jay-parti

**Comment by jenna1k** [comment]
PC 이미지 변경하였습니다
![image](https://user-images.githubusercontent.com/20438637/108010748-eeb92780-7048-11eb-88bb-4051819df9e4.png)

**Comment by anne-parti** [comment]
그룹 설정에서 수정 가능한 작업 + 개발 이슈가 아니라 대기로 이동합니다. 이미지 수정 완료 시에 다시 테스트 완료로 이동할게요.

**Comment by anne-parti** [comment]
@jay-parti 노란색 들어간 확정 이미지로 수정된 것 같은데 적용 확인 후에 이슈 닫아주세요. 감사합니다.
