### ISSUE TITLE
[YWCA] 추가 수정사항 

### ISSUE THREAD

**Issue by Dandi-hwang** [parti-coop/parti-mx-spa#12]
- [x]  탭 이름 변경 :  YWCA 평화갤러리
![image](https://user-images.githubusercontent.com/65291782/97951029-2377da80-1ddc-11eb-84f1-452bd2416882.png)

- [x] 사이트 타이틀 자리 : 맨 위에 있는 한국YWCA연합회는 띄어쓰기 없이 붙여주시기 바랍니다. 

![image](https://user-images.githubusercontent.com/65291782/97951244-de07dd00-1ddc-11eb-971a-68f798bb805f.png)

- [x] 푸터 Y홈페이지와 동일한 순서로.  / (로고는 넣을 수 없다고 얘기했음) 
 
이용약관 개인정보취급방침 
서울특별시 중구 퇴계로 18길 77(남산동 2가 45-6)
TEL 02-774-9702-7 FAX 02-774-9724
이메일 koreaywca@ywca.or.kr
Copyright 2020 한국YWCA연합회 All Rights Reserved.

- [x] 사이트 타이틀 - 글씨체도 Y로고와 동일하게.  - 고딕류. 로고/배너 이미지와 최대한 같게. 가능한가요? 

아래는 확인 후 작업 

- [x] 이용약관 (파일 링크) @제이 

- [x] 개인정보취급방침 (파일 링크) @제이

**Comment by iamswain25** [comment]
사이트 타이틀 글씨체를 Y로고와 같게 하는게 더 어려워서 홈페이지에서 로고 이미지를 다운 받아 넣었습니다... ㅜㅜ
