### ISSUE TITLE
[믹스] 소식게시판 댓글순 정렬시 무응답

### ISSUE THREAD

**Issue by mmx900** [parti-coop/parti-mx-spa#128]
1.0에서 소식게시판 댓글순 정렬시 내용이 표시되지 않습니다. 콘솔에 `FirebaseError: The query requires an index.` 메시지가 표시됩니다.

**Comment by iamswain25** [comment]
https://github.com/parti-coop/parti-mx-spa/blob/firebase/firestore.indexes.json 인덱스 배포가 안되었던 부분이네요. 인덱스 배포는 건 바이 건으로 하는 경우가 많아서, 보통 인덱스 에러 메시지 옆 링크를 클릭하여 인덱스 자동 추가를 합니다. 인덱스 추가는 시간이 좀 걸려서 10-20분 잡습니다.
