### ISSUE TITLE
[녹전연] 자체 테스트 이후 수정 요청사항 

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#132]
1차 테스트 이후 녹전연에서 주신 수정요청 사항입니다. 7번까지 있고, 추가 자잘한 문구 수정사항은 22일 오전에 전달받을 예정입니다. @anne-parti 

1. **키컬러 수정** #008083 → #4d8542 https://github.com/parti-coop/parti-mx-spa/issues/93
![image](https://user-images.githubusercontent.com/65703242/108480662-9731ea80-72da-11eb-999a-3a655d5814e4.png)

2. **홈**

- 사이트 타이틀 수정 ([이미지 링크](https://drive.google.com/file/d/1Jx4aqog6CGJSo-FFVbpTMkubHbNie0Wl/view?usp=sharing))  https://github.com/parti-coop/parti-mx-spa/issues/93
*보이는 높이가 [서사경](https://plan.sehub.net/home) 사이트 타이틀과 같았으면 합니다. (지금은 그보다 큰 것 같음)
**모바일에서도 사이트 타이틀이 조금만 더 작게 보이게 배치
- 홈 지도 초기 축적 : 현재 수도권 위주. 남한이 한번에 보이는 정도로 수정 https://github.com/parti-coop/parti-mx-spa/issues/87
![image](https://user-images.githubusercontent.com/65703242/108480627-8d0fec00-72da-11eb-9a65-33f615f60445.png)

3. **모임**
- 지도에서 모임 게시판 핀을 #f7a17e로 색상 적용
- 제안 게시판 공지 기능/디자인 추가와 동일하게 적용 https://github.com/parti-coop/parti-mx-spa/issues/84 
- 모임인원 0명부터 생성 가능하게 수정
![image](https://user-images.githubusercontent.com/65703242/108480496-6487f200-72da-11eb-9b35-179e266fc566.png)

4. **도서관**
- 입력버튼 : 소식 제출 → 게시하기
![image](https://user-images.githubusercontent.com/65703242/108480428-491ce700-72da-11eb-864d-2f4b84f351d4.png)

5. **주소** https://github.com/parti-coop/parti-mx-spa/issues/108
- 게시판별로 주소 입력필드에 다른 메세지를 넣을수 있을까요?
![image](https://user-images.githubusercontent.com/65703242/108480383-3acecb00-72da-11eb-83e3-94c283c18123.png)

- 가능하다면 
공론장 : 작성자님의 활동지역, 제안과 관련된 지역 등
모임 : 주최자님의 활동지역, 모임과 관련된 지역, 모임장소 등
도서관 : 자료와 관련된 지역 등 

- 주소 입력예시 수정
- 예) '광주광역시', '서울특별시 종로구 자하문로 17길 12-9'

6. **고정태그** : 아래 목록으로 수정부탁드립니다. 
어떻게_사회를_전환할_것인가
정의로운_전환
사회적경제
순환경제
돌봄·재난
에너지전환
건물·주거
교통·이동
농업·먹거리
생물다양성
문화·예술
교육
여성·소수자
디지털플랫폼
지역균형발전
기타
 
7. 자유태그(해시태그) 설명문구 수정
-  "주제 선택에서 '기타'를 선택했거나 주제보충이 필요한 경우 태그를 추가해주세요." 로 변경 부탁드립니다.
![image](https://user-images.githubusercontent.com/65703242/108669325-254ae280-7520-11eb-968c-41f35b187e5a.png)

**Comment by anne-parti** [comment]
@jenna1k 작업 부탁드립니다. 완료하고 알려주시면 테스트 진행할게요.

**Comment by jay-parti** [comment]
안나님이 확인하신 이후에 요청된 내용 (22일 오전 요청사항)도 추가해놓았습니다.  
정식오픈 전에 고정태그목록, 소개페이지 수정 가능성이 있다고 전달받았습니다. @anne-parti @jenna1k

**Comment by jay-parti** [comment]
추가요청사항이 와서 전달드립니다. 감사합니다. @jenna1k 
3. 모임
- '신청마감일'을 선택입력항목으로 수정

**Comment by anne-parti** [comment]
확인 완료했습니다. 
@jay-parti 님도 테스트, 확인 후에 이슈 클로즈 부탁드립니다~

**Comment by jay-parti** [comment]
감사합니다!! 정식 오픈 전 추가요청사항은 별도 이슈로 만들겠습니다.
