### ISSUE TITLE
[믹스] 로그인, 회원가입 관련 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#137]
**PC 버전**
- 메인
    - 상단 우측 '로그인' → `빠띠 믹스에 로그인`
    - 회원가입(https://parti-mx.web.app/signup) 타이틀 '회원가입' → `빠띠 믹스 회원가입`

**공통**
- 햄버거 메뉴 시 노출되는 레이어 타이틀 '믹스 그룹' → `빠띠 믹스`
- 회원가입(https://parti-mx.web.app/signup) 페이지 
    - 내용 보기 링크 변경
        - 이용약관 https://parti-mx.web.app/terms/service
        - 개인정보 처리방침 https://parti-mx.web.app/terms/privacy
        - 마케팅 정보 가능하다면 https://parti-mx.web.app/terms/privacy 내 맞춤형 정보 제공에 앵커 걸어서 링크 추가해주세요. 
    - 마케팅 수신 동의 → `마케팅 정보 수신 동의 (선택)`
- 프로필 (로그인 상태)
    - 마케팅 수신동의(선택) → `마케팅 정보 수신 동의`
    - 체크박스 레이블과 내용보기 사이 띄어쓰기 추가
    - 내용보기 링크 회원가입 페이지와 동일하게 변경

**Comment by mmx900** [comment]
@anne-parti 수정하여 확인 부탁드립니다.

현재 약관 클릭시 스크롤 위치가 조금 이상하게 잡히는 문제가 있는데 별도 이슈로 수정 예정입니다.

**Comment by mmx900** [comment]
@anne-parti 약관 새 창으로 열기 적용되었습니다.

**Comment by anne-parti** [comment]
@mmx900 마케팅 정보 스크롤 위치 외에는 확인 완료했습니다 👍
