### ISSUE TITLE
[믹스] 프로필 페이지에서 로그아웃 시 메인으로 이동

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#138]
현재 프로필 수정 페이지에서 로그아웃 버튼 클릭 시 상단의 상태만 변경되고 프로필 페이지에 그대로 남아있습니다.
프로필 페이지에서 로그아웃 시 현재 그룹 홈으로 이동하도록 수정해주세요.

**Comment by mmx900** [comment]
@anne-parti 수정하여 확인 부탁드립니다.

**Comment by anne-parti** [comment]
@mmx900 수정된 것 확인했습니다 👍
