### ISSUE TITLE
[믹스] 사파리에서 배너 노출안됨, 사이트 타이틀 폰트 깨짐현상

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#15]
사파리로 접근할 경우 아래 현상이 모바일, 맥북에서 모두 나타납니다. 
1. 배너 뜨지 않습니다. 
2. 사이트 타이틀 폰트가 깨집니다. 

아래는 참고이미지

<img width="1270" alt="믹스_사파리 깨짐(맥북)" src="https://user-images.githubusercontent.com/65703242/98511532-2aa15b80-22a8-11eb-9abb-734855b54dac.png">

![믹스_사파리 깨짐](https://user-images.githubusercontent.com/65703242/98511275-d5654a00-22a7-11eb-8419-d566fa3b509e.jpg)

**Comment by jay-parti** [comment]
동일한 현상이 [액션플랜 그룹](https://parti.mx/home?group_id=93)에서도 나옵니다. @iamswain25 

![image](https://user-images.githubusercontent.com/65703242/100206506-c1794380-2f49-11eb-9750-a3229e13726a.png)

**Comment by jay-parti** [comment]
저번에는 사파리에서만 오류가 났었는데요. 지금 확인해보니 크롬, 카톡으로 접근했을 때도 동일하네요.(모바일)
이미지처럼 모바일에서 배너가 안뜨면 회원가입도 불가능한걸로 알고 있습니다. (이미지는 본문 밑에 넣겠습니다)

내일 오후 6시에 행사가 있는데요. 제안 업로드 하는 순서가 있습니다. 
주민자치 작업 때문에 바쁘신걸로 알고 있는데요. 해결이 가능할까요?  @iamswain25  

![image](https://user-images.githubusercontent.com/65703242/100830400-e704d080-34a6-11eb-85a5-207174844fdf.png)
![image](https://user-images.githubusercontent.com/65703242/100830407-e9ffc100-34a6-11eb-8b85-a31394eb00bf.png)

**Comment by iamswain25** [comment]
아이고 크리티컬하네요 바로 해결할게요
