### ISSUE TITLE
[믹스] 그룹 회원 수 표시 추가 

### ISSUE THREAD

**Issue by Doran-Parti** [parti-coop/parti-mx-spa#155]
각 그룹마다의 회원수를 볼 수 있는 곳이 없습니다.  
1.0으로 바뀌면서 볼 수 있는 곳이 딱히 마련이 안 된 것 같아요.

각 그룹 회원수를 볼 수 있으면 좋겠습니다. 
- 1안: 배너 위에 개설일과 본인 닉네임 뜨는 곳에 추가한다. 
- 2안: 회원관리로 들어가서 회원명단 맨 위에 가입자 수가 뜨게 한다.
 
*참조:  기존에는 그룹 배너아래 작은 글씨로 멤버 수가 떴고, '멤버' 글씨를 클릭하면 회원관리로 넘어갔었습니다.  
![image](https://user-images.githubusercontent.com/68227316/109115279-2f6c1b80-7782-11eb-8b27-2d6417109321.png)

**Comment by mmx900** [comment]
@Doran-Parti 기존 사이트 참고해서 1안대로 추가했습니다. 확인 부탁드려요.

**Comment by Doran-Parti** [comment]
@mmx900 확인 했습니다! 감사해요.
