### ISSUE TITLE
[믹스] 중복투표 글의 댓글에 투표내용 표시 관련

### ISSUE THREAD

**Issue by Doran-Parti** [parti-coop/parti-mx-spa#156]
(스탠드업 등 세션에서도 이야기 나누었고, 파악하고 계신다고 하셨지만 깃헙에 없는 것 같아 적어봅니다!)
투표글에 투표한 후 댓글을 달면 이름 옆에 투표한 사항이 뜨지요. 그에 관련된 내용입니다. 

- [x] 중복투표에서 여러 개 선택한 사람도 댓글에 투표한 항목은 1개만 표시되고 있습니다. 여러 개 선택했을 경우 여러 개가 뜨도록 해야겠습니다. 

- [x] 중복투표 시 선택한 항목이 줄글로 뜨면 너무 길어 가독성이 떨어지기 때문에 이모티콘 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣🔟 으로 띄우도록 개선 (1.0 로드맵 내용)

**Comment by mmx900** [comment]
적용되었으나, 이모티콘으로 대체하는 부분은 새로 만든 게시물에만 적용됩니다.
기존 항목의 경우 마이그레이션 과정에서 일부 정보 누락이 있어서 #142 종료 후 적용될 예정입니다.
확인 부탁드립니다. @Doran-Parti

**Comment by Doran-Parti** [comment]
넵 확인했습니다. 감사합니다!
