### ISSUE TITLE
[믹스] 투표 퍼센트가 바르게 계산되어 나오지 않습니다. 

### ISSUE THREAD

**Issue by Doran-Parti** [parti-coop/parti-mx-spa#158]
전체 투표 수 중 해당 선택지의 득표율이 몇%인지 계산해서 보여주지 않고
한 표당 100%로 나오네요 ㅎㅎ
마이그레이션 이후 등록된 게시글에 한한 문제로 보입니다. 
https://parti.mx/post/OmPplAGUWgUtjkTWh4mF 

![image](https://user-images.githubusercontent.com/68227316/109257271-25f2ba00-783b-11eb-8107-20dc7eeffbc9.png)

**Comment by mmx900** [comment]
재현이 되지 않아 닫습니다. 재발하거나 재현 케이스가 확인되면 다시 열어주세요.
