### ISSUE TITLE
[녹전연] 정식오픈 전 요청사항

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#160]
정식오픈 (3/3) 전 요청사항입니다. @anne-parti 

1. 고정태그 수정
어떻게_사회를_전환할_것인가
정의로운_전환
사회적경제
순환경제
에너지전환
건물·주거
교통·이동
농업·먹거리·채식
생물다양성
돌봄·복지
여성·소수자
재난·회복
문화·예술
교육
자치분권·지역균형발전
디지털·플랫폼
기본소득·기후금융
기타

2. og 이미지 교체
파일 : https://drive.google.com/file/d/1iSwQJhno8KdTx4krAAboFyFOj0Uvi42G/view 

3. 사이트 타이틀 이미지 교체
파일 : https://drive.google.com/file/d/1Jx4aqog6CGJSo-FFVbpTMkubHbNie0Wl/view

4. 도서관_수정버튼 교체 
- 소식 수정 → 수정하기

5. 모임 게시판
기능추가 문의입니다. 모임장소가 링크일 때 클릭으로 이동할 수 있도록 구현 가능한지 문의. 
![image](https://user-images.githubusercontent.com/65703242/109583490-555b3c80-7b43-11eb-8b77-e03517977e81.png)

6. 소개 페이지 수정 
기존에서 문구, 이미지가 수정되었는데요. 레셈님께 디자인 요청 드리겠습니다.
문구 수정은 제나님이 해주시면 된다고 하시네요. 감사합니다. 

[페이지 문구]( https://docs.google.com/document/d/1itvlJ0ykiUwMU-sVKrJpXW8ZwdHpKSzHGELtw-Pv8Mw/edit) 
삽입 이미지
- [공론 프로세스](https://drive.google.com/file/d/15W_biGaTr9NSYbWhzoWwiXgDdzFg7e69/view?usp=sharing)
-[녹색오리 이미지](https://drive.google.com/file/d/1ioKrBgGODX_vnVeD3EJbk5VDvP6j00wU/view?usp=sharing)

-끝-

**Comment by anne-parti** [comment]
@jenna1k 5번은 일정 내 가능여부 확인 후 작업 부탁드립니다.

**Comment by jenna1k** [comment]
> @jay-parti 5번은 추가 기능이라 일정 내에 어려울 수 있습니다.
> @jenna1k 5번은 일정 내 가능여부 확인 후 작업 부탁드립니다. 감사합니다~

모임장소가 https:// 로 시작될 경우에만 링크를 적용하였습니다

**Comment by anne-parti** [comment]
@jenna1k 

소개 페이지 
1. 과정 이미지 상단 타이틀을 변경해주세요. 공론 절차와 공론 활용 방안 → `공론화 과정과 공론 활용 방안`
2. 하단 메일 주소에 mailto:igt.greenduck@gmail.com 를 추가해주세요. 

@jay-parti 
위 2개 내용 외에는 요청하신 수정사항 모두 반영된 것 확인했는데요. 제이님도 확인 부탁드립니다!
