### ISSUE TITLE
[녹전연] 도서관_첨부파일 게시 오류

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#161]
도서관 게시판에서 첨부파일 오류가 난다고 합니다. 게시할 수 없다고 하시는데요. 녹전연에서 전달해주신 파일입니다.(총 3개) 
@anne-parti @jenna1k 

[오류파일](https://drive.google.com/drive/u/0/folders/1SWegHHZaFVuQ7A__eH83GMuvKIBgPbRn)

**Comment by anne-parti** [comment]
@jenna1k 
1. 저는 업로드는 정상적으로 되고 첨부한 파일이 다운로드되지 않습니다. 다운로드 버튼 눌러도 다운로드가 시작되지 않습니다.
2. 녹전연에서는 게시가 안되는 문제가 있었다고 합니다. 
두 부분 모두 확인 부탁드립니다~

**Comment by jay-parti** [comment]
오류 관련 정보 추가합니다. @jenna1k 

사용 기기 : 맥북
사용 브라우저 : 크롬
오류메시지 : 별도 메시지 뜨지 않고, 반응이 없었음
첨부파일 순서 : 각각 한 게시물에 한 파일씩 시도 
녹전연에서 업로드 시도한 파일은 위에 링크 달아놓았습니다.

**Comment by iamswain25** [comment]
> @jenna1k
> 
> 1. 저는 업로드는 정상적으로 되고 첨부한 파일이 다운로드되지 않습니다. 다운로드 버튼 눌러도 다운로드가 시작되지 않습니다.
> 2. 녹전연에서는 게시가 안되는 문제가 있었다고 합니다.
>    두 부분 모두 확인 부탁드립니다~

https://github.com/parti-coop/parti-mx-spa/blob/hosting/green-newdeal/README.md#file-download @jenna1k 제나님 파일 다운로드는 이거 설정해야 하는데, 제가 잊고 하지 않은 것 같네요. 제가 설정해놓겠습니다.

**Comment by jenna1k** [comment]
> > @jenna1k
> > 
> > 1. 저는 업로드는 정상적으로 되고 첨부한 파일이 다운로드되지 않습니다. 다운로드 버튼 눌러도 다운로드가 시작되지 않습니다.
> > 2. 녹전연에서는 게시가 안되는 문제가 있었다고 합니다.
> >    두 부분 모두 확인 부탁드립니다~
> 
> https://github.com/parti-coop/parti-mx-spa/blob/hosting/green-newdeal/README.md#file-download @jenna1k 제나님 파일 다운로드는 이거 설정해야 하는데, 제가 잊고 하지 않은 것 같네요. 제가 설정해놓겠습니다.

감사합니다,  cors 설정하고 다운로드 되는거 확인했습니다

**Comment by jenna1k** [comment]
업로드 관련 오류는 발견하지 못했습니다. 
파일의 크기가 크거나 여러 파일을 첨부하는 경우 업로드 시간이 걸릴 수 있습니다.
녹전연측에 다시 시도를 부탁드립니다!

**Comment by jay-parti** [comment]
감사합니다. 녹전연에 재시도 후 오류 발생하면 연락달라고 했습니다. 
현재 오류는 발견하지 못한걸로 파악해서 클로즈 하겠습니다.
