### ISSUE TITLE
[녹전연] 모임 게시판_ 이미지 첨부 오류

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#162]
이미지 첨부시 게시가 안된다는 오류입니다. 아래가 해당 게시물인 것 같구요. 이미지 없이 글만 게시하셨습니다. 
https://greenduck.kr/post/rDrFeGFqQJIVxnvcxL07

저는 테스트 페이지에서 이미지 첨부 테스트시에는 문제없이 게시되었습니다. 
오류사항 확인 부탁드립니다~! @jenna1k

**Comment by jenna1k** [comment]
버그가 어떻게 재현되었는지 알 수 없으면 오류사항 확인이 어렵습니다.
파일첨부 오류와 이미지 첨부 오류 모두 녹전연측에서 어떤 단계로 첨부했는지 설명이 필요합니다.

**Comment by jay-parti** [comment]
바쁘실텐데 번거롭게 해드렸습니다.  어느 정도의 정보를 드리면 확인이 가능하실까요? 사용 브라우저, 해당 파일 정도면 될까요?

**Comment by jenna1k** [comment]
사용 브라우저, 해당 파일, 오류메세지(발견시), 오류가 났을때의 첨부 순서를 설명 부탁드립니다!

**Comment by jay-parti** [comment]
오류 관련 추가정보 드립니다. 감사합니다!  @jenna1k 

사용기기 : 맥북
사용 브라우저 : 크롬
오류 메시지 : 모임 생성을 눌러도 반응이 없음
해당 파일(이미지) : [링크](https://drive.google.com/file/d/1bwVl_k_vUoi6GuKj2b_ywkABkKt_nfeK/view?usp=sharing)

**Comment by jenna1k** [comment]
해당 게시물에 이미지 업로드 했습니다.
