### ISSUE TITLE
[믹스 X 셰어런팅] 홈 이미지 교체

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#163]
홈에서 노출되는 이미지 변경 요청드립니다. @dalikim 
오늘(3/2) 런칭 예정이라고 하시네요. 반영 가능한 일정도 알려달라고 하셨습니다.

[페이지_예시_1](https://drive.google.com/file/d/1wIYoPQl6U6HbxwuFlfSbZ6nEthPPzbYB/view?usp=sharing)
[페이지_예시_2](https://drive.google.com/file/d/1c5i3yEv82Gt5B58e4LC4xU1tNF3JdRvL/view?usp=sharing)

자세한 맥락은 [메일](https://mail.google.com/mail/u/0/#inbox/FMfcgxwLsdGLTxdBxTwPsskrRrFbVsfg) 확인 부탁드립니다.

**Comment by jenna1k** [comment]
제가 작업하겠습니다
