### ISSUE TITLE
[믹스 x 셰어런팅] 구글 애널리틱스 연결

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#168]
구글 애널리틱스 연동 요청입니다. 
더불어, 작업 완료일정도 함께 알려주시면  감사하겠습니다. @jenna1k (@anne-parti )

1. 코드 삽입 요청 
코드를 별도로 보내주셨는데요. 이미 애널리틱스가 연결되어있다면, 이 코드는 필요없는걸까요? 

<script async src="https://www.googletagmanager.com/gtag/js?id=G-F08ZBBFSW9"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());

 

  gtag('config', 'G-F08ZBBFSW9');

</script>

2. 셰어런팅에 구글애널리틱스 연동이 되어 있다고 알고 있는데요. 
우현님 계정이 관리자로 추가됐는지, 이용하실 수 있는 상태인지 확인이 필요할 것 같습니다. 
이용 가능한 상태라면 접근 방법 알려주시면, 전달하겠습니다.

**Comment by jenna1k** [comment]
이미 연동되어 있습니다.
우현님 메일 주시면 관리자로 추가하겠습니다.

**Comment by jay-parti** [comment]
[위키](https://union.parti.xyz/posts/38199) 살펴보니 whkoh.sckorea@gmail.com 로 구글애널리틱스 연결요청이 있었는데요. 
우현님(담당자)께 이 메일로 로그인 해서 접근하시면 된다고 하면 될까요? 아니면 새로운 메일을 달라고 요청드려야할까요?

**Comment by jenna1k** [comment]
위의 이메일로 sharenting-mix 구글애널리틱스 수정, 공동작업, 조회 및 분석 권한을 드렸습니다.

**Comment by Dandi-hwang** [comment]
> 위의 이메일로 sharenting-mix 구글애널리틱스 수정, 공동작업, 조회 및 분석 권한을 드렸습니다.

확인 감사합니다. 아주 쉬운 것이겠지만...접속 방법을 못찾으셔서 (저도요...) 

접근 경로를 알려주실 수 있을까요?

**Comment by jenna1k** [comment]
> > 위의 이메일로 sharenting-mix 구글애널리틱스 수정, 공동작업, 조회 및 분석 권한을 드렸습니다.
> 
> 확인 감사합니다. 아주 쉬운 것이겠지만...접속 방법을 못찾으셔서...
> 
> 접근 경로를 알려주실 수 있을까요?
> 
> 제가 찾은 건 이 페이지인데요.
> https://analytics.google.com/analytics/web/?hl=ko#/p250071998/reports/defaulthome?params=_u..nav%3Ddefault 요걸 드리면 될까요?

네, 맞습니다!
