### ISSUE TITLE
[믹스YWCA] 긴급 - 운영자 지정 asap

### ISSUE THREAD

**Issue by Dandi-hwang** [parti-coop/parti-mx-spa#20]
운영자 지정 요청
peacenow@ywca.or.kr
dandi@parti.coop 

(멤버로 변경되어 있음. 버그라면 해결 필요. 왜그럴까요? )

**Comment by iamswain25** [comment]
저도 운영자 취소되어 있는데,
jay@parti.coop
mix@parti.coop
두 계정은 여전히 운영자로 되어 있네요.
바뀌는 시스템에서 권한 작업은 로그를 남기도록 하겠습니다...
