### ISSUE TITLE
[믹스] 게시물 내 여러사진 삭제 시 첫번째가 먼저 지워지는 버그

### ISSUE THREAD

**Issue by Dandi-hwang** [parti-coop/parti-mx-spa#22]
(문제 상황 파악이 잘 안됨...추가 테스트/ 조건 확인 필요) 

홈페이지 수정을 하는데 오류가 생겨서 여쭙니다.
게시물에서 사진 지우기를 하면 무조건 맨 앞에 있는 사진이 지워집니다. 
일단 다 지우고 다시 올리는 방식으로 했습니다만, 왜 그런 걸까요...? 
며칠 전에 할 때에는 문제가 없었습니다. 
일단 사진을 맨 앞으로 보낸 뒤 삭제하는 방식으로 하고 있습니다 ㅋ

**Comment by iamswain25** [comment]
이건 다른 사이트도 마찬가지 오류가 있군요.. 일단 ywca는 해결했습니다.
