### ISSUE TITLE
[믹스] 서사경 커버 

### ISSUE THREAD

**Issue by murinono** [parti-coop/parti-mx-spa#30]
서사경 브랜드 가이드 : https://drive.google.com/file/d/1k0IIJTdJTopnXubYyro8nG1piYRzF_rj/view 
이미지: 유료 사이트 clipartkorea.co.kr
폰트: 서울시 서체 또는 오픈소스 서체 사용 
믹스 시범: https://parti.mx/home?group_id=93  
믹스 디자인가이드: https://drive.google.com/drive/folders/1INJ4VPsm_N5rvPILUPYFiX9553ptcz46 
데스크탑drive.google.com/drive/folders/1INJ4VPsm_N5rvPILUPYFiX9553ptcz46용 배너 
이미지 스펙 1140px X 270 px, 72 dpi, png or jpg
A영역 : 그룹명과 그룹 정보영역입니다. 비워주세요.
B영역 : 정보성내용은 해당 영역에 위치에 넣어주세요(로고/심볼 등 중요정보)
프리뷰 레이어 켜서 최종반영될 이미지 확인해주세요  
모바일용 배너 
이미지 스펙 720pxX360px, 72 dpi, png or jpg
A영역 : 정보성내용은 해당 영역에 위치에 넣어주세요(로고/심볼 등 중요정보)
프리뷰 레이어 켜서 최종반영될 이미지 확인해주세요

**Comment by murinono** [comment]
- [ ] 데스크탑 커버

- [ ] 모바일 커버 

- [ ] og 이미지 

- [ ] 파비콘

**Comment by Dandi-hwang** [comment]
@murinono 베리님, 혹시 배너 디자인이 20일까지 가능할까요? 마감을 저희가 미리 드리지 않았었는데, 워크숍 기획이 확정되면서 빠르게 오픈되면 좋겠다는 요청이어서요.

**Comment by iamswain25** [comment]
@murinono 제플린에 올려주신 이미지 파일 다운로드가 안되는데 확인 부탁드릴게요.

**Comment by murinono** [comment]
@iamswain25 안녕하세요,

1. 제플린에 올렸던 이슈는 서사경이 아니라 https://github.com/parti-coop/design-guild/issues/37 어울림축제 디자인입니다. 혹시 여기 이슈에 남기신 이유가 있으실까요? 
2. 제플린 주소 https://app.zeplin.io/project/5e75cccc0e5c196e22cddd3c/dashboard?seid=5fc7380f995dd30e6087f7b1 에서 푸터 영역에 있는 이미지들은 다운로드가 되는 것으로 확인됩니다. 커버 이미지를 말씀하시는 것이라면 깃헙 이슈에 업로드해두었습니다.

**Comment by iamswain25** [comment]
> @iamswain25 안녕하세요,
> 
> 1. 제플린에 올렸던 이슈는 서사경이 아니라 [parti-coop/design-guild#37](https://github.com/parti-coop/design-guild/issues/37) 어울림축제 디자인입니다. 혹시 여기 이슈에 남기신 이유가 있으실까요?
> 2. 제플린 주소 https://app.zeplin.io/project/5e75cccc0e5c196e22cddd3c/dashboard?seid=5fc7380f995dd30e6087f7b1 에서 푸터 영역에 있는 이미지들은 다운로드가 되는 것으로 확인됩니다. 커버 이미지를 말씀하시는 것이라면 깃헙 이슈에 업로드해두었습니다.
> 3. 확인되시면 이슈 클로즈 하겠습니다.

1. 제가 착각했습니다. 2. 커버 이미지 확인했습니다! 3. 감사합니다!!
