### ISSUE TITLE
[주민자치박람회] 우수사례 전시 틀 수정

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#34]
<img width="767" alt="스크린샷 2020-11-21 오후 4 21 05" src="https://user-images.githubusercontent.com/58158305/99871207-ed2fbd00-2c1b-11eb-9dfc-b768a742ad62.png">
@iamswain25 템플릿에 심사평 다음에 자세히 보기가 있는데 현재는 심사평 위에 자세히 보기가 있습니다! 이부분 확인부탁드립니다.

**Comment by anne-parti** [comment]
@sshony  아래 순서대로 표시돼야하는게 맞나요? [테스트 페이지](https://policy-fair-mix.web.app/post/q6yuc7dlMebYRBk04uAn)에서 확인 부탁드립니다. 

- 단체명
- 요약
- 심사평
- ---- 자세히보기
- 일반현황
- 대표사례

**Comment by sshony** [comment]
@anne-parti 네 단체명 요약 심사평 ---자세히보기 일반현황 대표사례 맞습니다!
