### ISSUE TITLE
[주민자치박람회] 닉네임 변경 요청

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#36]
<img width="739" alt="스크린샷 2020-11-22 오전 12 21 35" src="https://user-images.githubusercontent.com/58158305/99881946-491c3500-2c60-11eb-949b-811b7d540a4b.png">

@iamswain25 contact승인이 안나서 일단 제아이디로 작성했더니 sshony라고 보이네요. 이걸 제19회전국주민자치박람회 사무국으로 변경하고 싶습니다. 가능한지 궁금합니다.

**Comment by iamswain25** [comment]
![스크린샷 2020-11-25 11 17 45](https://user-images.githubusercontent.com/15191725/100174658-2e6fe780-2f10-11eb-8b5d-7e0cf8475eb4.png)
이 부분 클릭하면 아래 페이지로 들어가게 되어 수정할 수 있습니다. https://policy-fair-mix.web.app/profile 
디자인 되지 않은 부분이라 일단 임의로 우측 상단에 넣었어요.
