### ISSUE TITLE
[주민자치박람회] 태그 수정 요청

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#37]
<img width="440" alt="스크린샷 2020-11-22 오전 2 31 13" src="https://user-images.githubusercontent.com/58158305/99896950-976d1a80-2cd8-11eb-8602-00614d58fa92.png">

@iamswain25 자동태그에 지역활성화 학습공동체 주민조직네트워크 등은 하나의 태그가 생겨야하는데 띄어쓰기 때문인지 나눠서 태그가되네요. 띄어쓰기를 없애더라도 하나로 태그되게 부탁드립니다.

**Comment by sshony** [comment]
@iamswain25 내일 우수사례 선정되신분들이 글쓰실 예정이신데 아직 태그가 위에처럼 나눠져서 걸려서 지역활성화 클릭해도 지역활성화글이 걸러지지 않네요. 확인한번부탁드립니다.

**Comment by anne-parti** [comment]
언더바로 변경한 것 확인했습니다~
