### ISSUE TITLE
[주민자치박람회] 우수사례 전시 갯수 조정 또는 이미지 화소 조정

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#38]
<img width="1168" alt="스크린샷 2020-11-22 오전 2 27 05" src="https://user-images.githubusercontent.com/58158305/99897004-0ea2ae80-2cd9-11eb-9f77-af3a2ff83d58.png">
@iamswain25 다른게시판은 4개씩 배치되는데 전시는 3개 배치로 되어있는 상태입니다. 혹시 이걸 4개로 바꿀수있는지 아니면 대문화소를 아무리 높여 만들어도 대문이 보이다 싶이 이미지가 조금 흐릿하게 깨져보입니다. 클릭하고 들어가서 보는 이미지는 깔끔한데ㅠㅠ 4개 배치에서는 이미지가 조금 깨져도 티가 덜나는데 3개 배치는 티가 많이 나서 이미지 화소를 높일 방법이나, 또는 3개 배치를 4개로 바꿀수있는 상황인지 궁금합니다.

**Comment by anne-parti** [comment]
메인화면에 3개씩 노출되는 것 확인했습니다~
