### ISSUE TITLE
[주민자치박람회] 토론게시판 오류

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#39]
@iamswain25 투표 게시판 글 작성 후 클릭하면 내용없이 하얀 화면이 나옵니다. 아직 구성이 다 안된건지 오류인지 몰라 일단 남겨둡니다.

**Comment by anne-parti** [comment]
@sshony @iamswain25 
투표 작성 시 전반적으로 오류 없이 등록되지만 특정 상황에서 보기 항목에 오류가 발생하는 것으로 보입니다. (https://github.com/parti-coop/parti-mx-spa/issues/53 참고)
쇼니님이 테스트하신 상황이 어떤 상황인지 확인이 필요해보입니다.

**Comment by sshony** [comment]
@anne-parti 초반에 작업하실때 글 등록해서 발생한 문제같아요. 투표 게시판에 글 등록했는데 내용이 안보이고 하얀하면만 떴습니다. 현재는 내용이 잘 보여서 문제없어보이긴 한데. 투표에 추가로 글등록 몇개 더 해보도록하겠습니다.

**Comment by anne-parti** [comment]
@sshony 네네 특정 상황에서 오류가 발생하는데 그건 따로 이슈로 등록해두었어요. 최초에 발생한 오류가 더이상 발생하지 않으면 https://github.com/parti-coop/parti-mx-spa/projects/1 이 페이지의 토론 게시판 오류 카드를 '재확인 필요'에서 'Done'으로 옮겨주세요. 감사합니다!!

**Comment by sshony** [comment]
@anne-parti 추가확인후 이동해놓겠습니다! 감사합니다!
