### ISSUE TITLE
youthwagle 활동 내역 csv 파일 다운로드 요청

### ISSUE THREAD

**Issue by Dandi-hwang** [parti-coop/parti-mx-spa#4]
@dalikim  

대학내일(청년참여 거버넌스 - https://youthwagle.kr/ ) 사용자별 월별 활동 통계 요청. 

* 요청 기간 
: 오픈 이후 ~ 8월 31일.(월간 통계 필요) 
* 요청 내용 
: 회원(아이디)별 게시물 작성수, 댓글수, 공감수, 로그인횟수 확인가능한 엑셀 또는 csv 파일 
: (그룹 내 제안게시판만 한정해서 집계 가능한지도 문의왔음. youthwagle은 6개 그룹 운영 중. 5개 그룹에 제안게시판 있음. 리스트에서 그룹/게시판 필터를 사용할 수 있는 형태로 데이터가 정리된다면  굳이 구분해서 주지 않으셔도 됩니다.)

서원 :  
https://api-univ-tomorrow.parti.mx/console/api-explorer / ************************ (암호는 슬랙 검색)
여기 들어가셔서 graphql query로 데이터를 뽑을 수 있습니다. 제가 쿼리는 만들었는데, json이에요. 엑셀이나 csv로 변환해서 넘겨줘야 할 것 같습니다.

(앞으로 영등포문화재단, 작은도서관에서도 요청이 있을 예정입니다)

**Comment by dalikim** [comment]
오래 기다렸을텐데 지금 보니 서원님께서 만들어 주신 쿼리에 그룹/게시판별 필터가 없네요.
우선 아래는 서원님 주신 것으로 뽑은 데이터예요. 

1. 서원님 연락되면 다시 업데이트 할께요.
2. 급한데로 아래 데이터를 1차 공유하고 추후 업데이트 한다고 이야기 할 수도 있을까요? 

https://docs.google.com/spreadsheets/d/1H8a02y-edhXLI19ICXbIgpBQKCkHHfeeBUEWmokTLUQ/edit#gid=303686468

**Comment by iamswain25** [comment]
현재 그룹 1개, 게시판 1개만 쓰고 있습니다.

**Comment by iamswain25** [comment]
```
query{
  mx_users {
    email
    name
    comments_aggregate(where:{post:{board_id:{_eq: 1}}}) {
      aggregate {
        count
      }
    }
    createdPosts_aggregate(where:{board_id:{_eq: 1}}) {
      aggregate {
        count
      }
    }
    checkedPosts_aggregate(where:{post:{board_id:{_eq: 1}}}) {
      aggregate {
        sum {
          like_count
        }
      }
    }
  }
}
```
이런식으로 게시판 아이디를 넣어 필터링을 할 수 있습니다.
그룹 필터링은 아래와 같습니다.
```
query{
  mx_users {
    email
    name
    comments_aggregate(where:{post:{board:{group_id:{_eq: 1}}}}) {
      aggregate {
        count
      }
    }
    createdPosts_aggregate(where:{board:{group_id:{_eq: 1}}}) {
      aggregate {
        count
      }
    }
    checkedPosts_aggregate(where:{post:{board:{group_id:{_eq: 1}}}}) {
      aggregate {
        sum {
          like_count
        }
      }
    }
  }
}

```

**Comment by dalikim** [comment]
@Dandi-hwang ( @Doran-Parti )

게시판 아이디와 이름 목록을 주실 수 있을까요?

**Comment by jay-parti** [comment]
@dalikim 최초로 만들어주신 파일 전달드렸어요. 업데이트 되는 파일에는 회원구분(운영자, 참여단, 패널)도 같이 넣어주실 수 있을까요?

**Comment by dalikim** [comment]
> @dalikim 최초로 만들어주신 파일 전달드렸어요. 업데이트 되는 파일에는 회원구분(운영자, 참여단, 패널)도 같이 넣어주실 수 있을까요?
> 
> ( @iamswain25 께 살포시 멘션해 봅니다 - @달리 )

@jay-parti   여기에 파일 업로드 해주세요. 드래그앤드롭하면 됩니다.

**Comment by jay-parti** [comment]
@dalikim 이 파일 말씀하신 것 맞을까요? 달리님이 스프레드시트로 전달해주신 걸 엑셀로 다운 받아서 전달드렸어요. 
[youthwagle_2020년 9월 1일 18시00분.xlsx](https://github.com/parti-coop/parti-mx-spa/files/5159806/youthwagle_2020.9.1.18.00.xlsx)

**Comment by dalikim** [comment]
> @dalikim 이 파일 말씀하신 것 맞을까요? 달리님이 스프레드시트로 전달해주신 걸 엑셀로 다운 받아서 전달드렸어요.
> [youthwagle_2020년 9월 1일 18시00분.xlsx](https://github.com/parti-coop/parti-mx-spa/files/5159806/youthwagle_2020.9.1.18.00.xlsx)

게시판 아이디와 이름 목록을 주세요.

**Comment by iamswain25** [comment]
회원구분 추가 쿼리도 넣었습니다. 
status에 오거나이저, 유저, 패널(participant) 로 구분합니다.

```
query{
  mx_users {
    email
    name
    status: groups(where:{group_id:{_eq: 1}}){
      status
    }
    comments_aggregate(where:{post:{board:{group_id:{_eq: 1}}}}) {
      aggregate {
        count
      }
    }
    createdPosts_aggregate(where:{board:{group_id:{_eq: 1}}}) {
      aggregate {
        count
      }
    }
    checkedPosts_aggregate(where:{post:{board:{group_id:{_eq: 1}}}}) {
      aggregate {
        sum {
          like_count
        }
      }
    }
  }
}

```

**Comment by jay-parti** [comment]
@dalikim 분과별 구분하고 게시판 아이디 는뒤에 붙였습니다. 

와글와글 정책실
- 공지사항  233
- 온라인 정책 아카데미 254
- 온라인 청년패널 설문결과 280 
 
교육 분과 
- 소식 263
- 제안 265 
- 투표 266 
- 모임 264 
- 자유 게시판 277

일자리 분과 
- 소식 255 
- 제안 257
- 투표 258 
- 모임 256 (게시물 없음)
- 자유 게시판 275
 

생활 분과 
- 소식 267
- 제안 269 
- 투표 270
- 모임 268 
- 자유 게시판 278

참여/권리 분과 
- 소식 271
- 제안 273
- 투표 274 
- 모임 272 
- 자유 게시판 279

주거분과 
- 소식 259
- 제안 261
- 투표 262 
- 모임 260 
- 자유 게시판 276

**Comment by jay-parti** [comment]
@dalikim 전에도 왔던 내용인데, 제안게시판 한정으로 통계가 가능한지 문의주셨어요. 어떻게 답변 드릴 수 있을까요?

**Comment by dalikim** [comment]
늦게 연락드려 죄송합니다. 아직도 이 작업 유효한가요?

**Comment by jay-parti** [comment]
네 달리님. 요청드린 사항으로 진행해주시면 될 것 같습니다. 
추가로 필요하신 것 있다면 다시 말씀주세요.
