### ISSUE TITLE
[주민자치박람회] 유튜브 링크 삽입시 깨짐 현상 및 작성자 변경 현상

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#40]
<img width="640" alt="스크린샷 2020-11-26 오전 2 36 13" src="https://user-images.githubusercontent.com/58158305/100264644-6fa8db80-2f92-11eb-8e13-b891a1fd3ebd.png">

학술행사 소개 게시판에 유튜브 링크를 추가하였더니 이렇게 깨져보이네요. 왜그런지 확인한번 부탁드립니다. @iamswain25 

<img width="666" alt="스크린샷 2020-11-26 오전 2 36 25" src="https://user-images.githubusercontent.com/58158305/100264719-8cddaa00-2f92-11eb-83f8-811d2e49f8ae.png">
더불어 작성자가 다 제19회 전국주민자치박람회 였는데 서원으로 변경되었어요~ 확인부탁드립니다. @iamswain25

**Comment by anne-parti** [comment]
@iamswain25 
1. 유튜브 미리보기는 수정 완료 확인했습니다. 
2. 작성자는 이 이슈 https://github.com/parti-coop/parti-mx-spa/issues/46 확인해주세요.
