### ISSUE TITLE
[주민자치박람회] 메인 이미지 우측 상단 정보+그룹 가입 영역 수정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#41]
@iamswain25 

<img width="390" alt="스크린샷 2020-11-26 오후 3 09 00" src="https://user-images.githubusercontent.com/55128558/100314481-12487500-2ffa-11eb-81bc-c06cfef1ab9f.png">

메인 이미지 우측 상단 그룹 개설일, 프로필, 그룹가입 버튼 삭제하고 아래처럼 수정했으면 합니다. 
1. GNB 로그인 왼쪽에 프로필(닉네임) 표시
    - 비로그인 시 익명, 클릭 시 익명 프로필 변경 가능 (익명에 대한 안내 필요..?)
    - 로그인 시 클릭 시 프로필 페이지로 이동
2. 현재 표시되는 정보는 오거나이저일 경우에만 표시
    - 그룹관리, 회원관리, 게시판 관리 가능

디자인 가이드 필요할 경우 알려주세요.

**Comment by iamswain25** [comment]
이부분을 늦게 봤는데, 모바일 화면에 대한 디자인 가이드가 필요합니다. 현재 지정해주신 부분이 가로가 줄어들었을 때 없어지는 부분이라 그렇습니다.

**Comment by anne-parti** [comment]
모바일 버전으로 접속 시 로딩 중 글자가 일시적으로 노출되는데 가림 처리 부탁드립니다~

**Comment by anne-parti** [comment]
모바일에서 테스트 완료했습니다~
