### ISSUE TITLE
[주민자치박람회] 공지 게시판 글 작성자 오류

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#46]
@iamswain25 
공지 게시판에 동일한 관리자 계정으로 글을 게시했는데 작성자 명이 다르게 나옵니다.
https://policy-fair-mix.web.app/home/sPnn8zdVEYxNrQS5MbtF

1. contact
2. 익명

**Comment by anne-parti** [comment]
@iamswain25 다른 게시판은 작성자가 "제19회 전국주민자치박람회" (띄어쓰기 있음) 인데요. 공지사항에는 띄어쓰기가 안되어 있습니다. 띄어쓰기 넣어서 통일해주세요.

**Comment by iamswain25** [comment]
아마 어떤건 쇼니님 계정으로 쓰고, 어떤건 contact@parti.coop으로 썼던 것 같아요. 지금 보니 쇼니님 계정이 띄어쓰기 한 것 같아서, 굳이 포스트마다 통일 시킬 필요가 있을까 싶네요.

**Comment by anne-parti** [comment]
@iamswain25 네 제가 닉네임을 수정했어요. 이번엔 프로필 사진 적용했더니 동일한 이슈가 발생하네요. 이 건은 이따 세션 때 다시 이야기 나눠봐야겠습니다~
