### ISSUE TITLE
[주민자치박람회] 비밀번호 재설정 이메일 발신 이메일 주소 변경

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#49]
@iamswain25 
우선순위는 낮은 이슈입니다. 

1. 비밀번호 재설정 이메일 발신 이메일 주소를 변경할 수 있나요?
    - noreply@juminexpo.kr 또는 
    - contact@juminexpo.kr

    내용은 제가 변경했는데 파이어베이스에서 발신자 주소 변경하려니 
    "도메인을 확인하려면 도메인 등록기관에서 다음 DNS 레코드를 추가하세요." 창이 떠서요. 
   저에게 방법을 알려주셔도 좋습니다. 

2. juminexpo.kr 로 도메인 연결 시 비밀번호 재설정 페이지 링크 주소도 변경되나요? 
현재는 이메일에서 재설정 링크 클릭 시 https://policy-fair-mix.firebaseapp.com/~ 로 시작하는 링크 주소가 노출됩니다.

**Comment by iamswain25** [comment]
1. https://dash.cloudflare.com/8b001c2ec1c9365982b1068e186cf18c/juminexpo.kr/dns 여기서 추가하는 부분인데, 제가 세팅했습니다. 방법은 다음에 자세하게 알려드리겠습니다. 

2. 당장은 바꾸기 힘들어요. 저 주소 안쓰려면 페이지를 직접 하나 만들어야 하는데, 아직 안만들었습니다.

**Comment by anne-parti** [comment]
비밀번호 재설정 이메일 주소 noreply@juminexpo.kr 로 도착하는 것 확인했습니다.
