### ISSUE TITLE
youthwagle 9/9 오류사항 및 기능점검 

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#5]
청년참여거버넌스에서 9/9일 확인, 수정요청주신 사항입니다. 금요일 오전 10부터 토요일 24시까지 투표진헹. 현재는 오류 확인차 테스트중.  @iamswain25 

맨 위에 배치한 오류 사항은 금요일 테스트 전에 확인되어야 할 것 같네요. **금요일부터 투표 진행예정인데 투표 포멧인
익명x 중복x 집계숨김o 이 제대로 작동을 하지 않음
https://youthwagle.kr/post/524** 

중복투표 불가로 설정해도 중복투표가능 한문제
https://youthwagle.kr/post/514 

댓글에 투표결과가 표기되는 문제
https://youthwagle.kr/post/521  

집계숨김 작동안함
https://youthwagle.kr/post/522 

테스트 그룹을 새로 생성했는데 다른 그룹 배너가 교체되는 문제
https://youthwagle.kr/home?group_id=107  (신설) 
https://youthwagle.kr/home?group_id=105

투표 정리 후 투표에 참여한 사람 리스트를 조회할 수 없음
https://youthwagle.kr/post/530
정리를 하고 나면 투표 결과에 대한 퍼센테이지가 출력이 되어야하는데 이부분이 표기가 안되고 있는 것 같음.

**Comment by Dandi-hwang** [comment]
@jay-parti 글쓴이만 종료 할 수 있군요. 이슈 종료 부탁드려요.
