### ISSUE TITLE
[주민자치박람회] BI 변경요청

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#51]
[박람회_BI.pdf](https://github.com/parti-coop/parti-mx-spa/files/5612336/_BI.pdf)
![박람회_BI](https://user-images.githubusercontent.com/58158305/100545193-0da3eb00-329e-11eb-8f0a-21427eae6e56.png)
@iamswain25 @leshem8 BI 만들어보았습니다. 확인부탁드립니다.

**Comment by anne-parti** [comment]
GNB PC/ 모바일 버전에 적용된 것 확인했습니다. @leshem8 님도 한 번 확인 부탁드려요.
