### ISSUE TITLE
[주민자치박람회] 홈화면 갯수 조절

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#52]
@iamswain25  작업 중이실듯하지만 혹시 잊으셨을까봐.ㅎ 현재 홈화면에 작성한 게시글이 모두 보이는 상태입니다.

우수전시외에는 최대 4개까지만 보이도록 조정부탁드려요.

**Comment by anne-parti** [comment]
현재 메인화면에 우수사례 3개 노출됩니다.

**Comment by anne-parti** [comment]
테스트 페이지에서 확인했습니다.
