### ISSUE TITLE
[주민자치박람회] 이미지 삭제 오류

### ISSUE THREAD

**Issue by sshony** [parti-coop/parti-mx-spa#57]
@iamswain25 우수사례전시 업로드한 이미지 삭제시 예를 들어 두번째 이미지를 삭제하려고 클릭하면 첫번째 이미지가 삭제됩니다. 전반적으로 삭제하려는 이미지 외 다른 이미지가 삭제되어 수정작업이 쉽지 않은 상황입니다. 점검한번 부탁드립니다.

**Comment by anne-parti** [comment]
@sshony 수정된 것으로 보이는데 테스트 한 번 부탁드립니다~!
