### ISSUE TITLE
[주민자치박람회] 메타 태그 설정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#58]
- OG 타이틀: 제19회 전국주민자치박람회
- OG 디스크립션: 전국 주민자치 사례를 발굴하여 상호학습하고 교류를 활성화하기 위해 제19회 전국주민자치박람회를 개최합니다.
- OG 이미지: https://juminexpo.kr/packs/media/images/og-9fc7ea6daf71fd44e4b6fabb9e9f72f3.png 

- 키워드: 전국주민자치박람회, 주민자치, 생활자치, 지역활성화, 주민자치회, 주민자치위원회, 주민협의회, 마을자치, 자치분권

- 페이지 타이틀: 제19회 전국주민자치박람회 - 새로운 연결, 세대가 함께 여는 주민자치

**Comment by iamswain25** [comment]
https://github.com/parti-coop/parti-mx-spa/commit/1bcf97000ae5ee96b5fa9eba67fd6d607d43fe5d
