### ISSUE TITLE
빠띠믹스_작은도서관 사업데이터 요청 

### ISSUE THREAD

**Issue by Dandi-hwang** [parti-coop/parti-mx-spa#6]
- [ ] 작은도서관 - 동대문 게시물 목록  
URL :  https://parti.mx/home?group_id=86 
양식 : 게시판 이름 - 게시물 제목 - 작성자 닉네임 - 작성일 - 게시물 URL

- [ ] 작은도서관 - 은평 게시물 목록 
URL :  https://parti.mx/home?group_id=87
양식 : 게시판 이름 - 게시물 제목 - 작성자 닉네임 - 작성일 - 게시물 URL

중간보고서 제출을 위해 게시물 목록 엑셀 파일이 필요합니다. 
마감 : 10/20(화) 오전

**Comment by iamswain25** [comment]
https://drive.google.com/drive/folders/14XD7H8YtfZZI52mQVsuhETzPeboLzbEd?usp=sharing
