### ISSUE TITLE
[주민자치박람회] IE로 접속 시 지원안함 안내 표시

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#60]
@iamswain25 IE로 접속 시 현재 빈 페이지가 뜨는데요. 지원안함 안내가 필요합니다.

GNB 영역에는 BI만 남기고 본문 영역은 타운홀 디자인 참고해서 작업해주세요.
- PC https://zpl.io/a3LM661
- 모바일 https://zpl.io/a7r6NnM 

메시지는 아래와 같이 수정해주세요.

> 제19회 전국주민자치박람회 웹사이트를 방문해주셔서 감사합니다.
> 
> 지원하지 않는 브라우저로 접속 시 이용이 제한될 수 있습니다.
> 웹사이트에 접속하려면 다른 브라우저를 이용하세요. 
> 
> 제19회 전국주민자치박람회 웹사이트는 Chrome, Microsoft Edge에 최적화되어 있습니다. 
> 문의하기 (mailto:contact@juminexpo.kr)

믹스 IE 지원 관련해서는 나중에 논의가 필요합니다~

**Comment by iamswain25** [comment]
https://github.com/parti-coop/parti-mx-spa/compare/780fb2cedf94...f897603bd333
