### ISSUE TITLE
[믹스] 게시판 관리 - 게시판 순서 변경 개선

### ISSUE THREAD

**Issue by jenna1k** [parti-coop/parti-mx-spa#63]
![image](https://user-images.githubusercontent.com/20438637/101115045-04ac7400-3626-11eb-80c6-fb12284b5234.png)

### 개선사항 제안

현재 게시판 관리 페이지에서 게시판 순서 변경시 유저가 임의의 숫자 기입 가능
![image](https://user-images.githubusercontent.com/20438637/101115614-fad74080-3626-11eb-8e5f-8dfc341ea331.png)

- [x] 게시판 갯수만큼 제한
- [x] TextField에서 Select로 변경

**Comment by iamswain25** [comment]
두번째 select 구현이 기대됩니다! 순서 정렬이 은근 어려워서 궁금합니다 ㅎㅎ

**Comment by Dandi-hwang** [comment]
(순서 정렬이 지금 온전히 구현이 안되서 고치고 싶었는데..기대됩니다.!! )
