### ISSUE TITLE
[서사경] 푸터 변경

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/parti-mx-spa#67]
https://sehub.net/
![image](https://user-images.githubusercontent.com/15191725/101437789-502b8e80-3954-11eb-9b9f-50bf7954f7de.png)
서사경 센터 푸터와 동일하게 적용
- [x] 데스크탑
- [x] 모바일
- [x] "적당한 위치" (ㅋㅋㅋ) 에 powered by parti 추가

**Comment by Dandi-hwang** [comment]
디테일 챙길 것들 내일 서사경-빠띠 회의에서 결정 후 깃헙에 올리겠습니다. 지금 논의 중인 문서는 https://union.parti.xyz/posts/39202 요기입니다.
