### ISSUE TITLE
[믹스X어울림축제] 활동 데이터 요청 ~(12/22)

### ISSUE THREAD

**Issue by Dandi-hwang** [parti-coop/parti-mx-spa#74]
- [x] 제안게시판 게시물별 공감수 리스트 : 게시물 제목 / 링크 / 공감수 / 댓글 수 (공감수 + 댓글수로 상품을 주기로 했네요) 
- [x] 회원 명단 : 닉네임 / 메일주소/ 지역 / 

[결과보고서 작성 중. 
](https://docs.google.com/document/d/1ePVxz7DYGXOfgXDUHxpFdR8qnbRaa7V4pKPRTZCwpgs/edit#)

@iamswain25

**Comment by partisoy** [comment]
요거 혹시 오전 중에 가능할까요?

**Comment by iamswain25** [comment]
https://drive.google.com/drive/folders/1qiYpMNrltycGSO3oTGQg8MHz5Lf-RwBy?usp=sharing
