### ISSUE TITLE
[녹전연] (상단 이미지 변경 필요) 소개 페이지 추가 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#83]
녹전연에서 작성한 콘텐츠 기반으로 GNB에 정적 페이지 추가
참고 ex. 민주주의 서울소개 페이지 https://democracy.seoul.go.kr/front/intro/faq/induList.do 

- [x] 콘텐츠 
- [x] 디자인 
    - [x] 메뉴 위치
    - [x] 상세 페이지 
- [x] 개발

**Comment by jay-parti** [comment]
녹전연 소개 페이지 [문구](https://docs.google.com/document/d/1itvlJ0ykiUwMU-sVKrJpXW8ZwdHpKSzHGELtw-Pv8Mw/edit#heading=h.nuf8tzpqwyt5) 전달드립니다.

질문) 텍스트에 색상, 삭선, 볼드체 등이 들어가 있는데요. 위 문서 구성대로 구현이 가능할까요? @anne-parti 
-참고로 삭선도 그대로 들어가는 텍스트입니다.

삽입 이미지는 아래 링크에서 확인하실 수 있습니다.
https://drive.google.com/file/d/1rirJ4bCm7JmZIpM7LGL-TZqaHBPnDBlX/view?usp=sharing

**Comment by anne-parti** [comment]
@iamswain25 별도 디자인 작업 필요한지 검토 부탁드립니다.

**Comment by anne-parti** [comment]
@jenna1k 레셈님이 디자인 가이드 전달해주셨어요 https://github.com/parti-coop/design-guild/issues/48#issuecomment-778967391 작업 부탁드립니다 감사합니다!

**Comment by jenna1k** [comment]
@anne-parti  확인 부탁드립니다

**Comment by anne-parti** [comment]
@jenna1k 첫번째, 마지막 문단에 띄어쓰기 안된데가 있어요. 강조 문장 끝나는 부분.. 스크린샷 첨부하니 수정 부탁드립니다. 
<img width="833" alt="스크린샷 2021-02-16 오후 2 26 53" src="https://user-images.githubusercontent.com/55128558/108022159-6005d400-7063-11eb-84c4-bfb3a375b32f.png">
<img width="834" alt="스크린샷 2021-02-16 오후 2 26 43" src="https://user-images.githubusercontent.com/55128558/108022161-61cf9780-7063-11eb-8275-4c4f774cb363.png">

@leshem8 님 폰트 크기가 좀 작은데 괜찮을까요? (특히 모바일..)

**Comment by anne-parti** [comment]
@jenna1k 다른 메뉴 접속 후에 소개 페이지로 이동(도서관→소개) 시 다른 메뉴 선택 비활성화가 안됩니다. 
<img width="402" alt="스크린샷 2021-02-16 오후 4 13 42" src="https://user-images.githubusercontent.com/55128558/108030105-f50fc980-7071-11eb-99a3-4364eb7ebb4c.png">

**Comment by anne-parti** [comment]
수정 완료 확인했습니다 👍

**Comment by jay-parti** [comment]
[소개 페이지](https://greenduck.kr/home/intro) 상단에 들어가는 이미지 교체요청입니다. 기존 이미지에서 변경된 이미지로 변경 요청드려요. @jenna1k 
<img width="650" alt="녹색오리 수정사항" src="https://user-images.githubusercontent.com/65703242/109922311-7b7a0b80-7d00-11eb-8c8f-0cc231ffd0c4.PNG">

[링크](https://drive.google.com/file/d/1D5Dnsd7_Eewc_At0u9aUdaA9lynpZyGH/view)에서 파일 확인하실 수 있습니다.

**Comment by anne-parti** [comment]
확인 완료했습니다. 이슈 클로즈 할게요 @jay-parti
