### ISSUE TITLE
[녹전연] 이용약관, 개인정보 처리방침 작성 및 추가 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#88]
- [ ] 이용약관, 개인정보 처리방침 작성 및 검토
- [ ] 문서 업데이트, 링크 생성
- [ ] 플랫폼에 연결
    - [ ] 푸터
    - [ ] 회원가입 하단 동의 체크박스

**Comment by anne-parti** [comment]
@jay-parti 
녹전연에 검토 요청드린 '개인정보 처리방침' 문서 보고 여쭤봅니다. 

수집 항목과 이용 목적
1. 필수항목
     - 회원가입 시 거주지(광역/시,군) 정보와 소속은 선택항목으로 알고 있는데요. 문서 내 `가. 필수항목`에 들어가 있습니다.  '거주지 정보'는 `나. 선택항목`으로 이동해주세요. 
2. 선택항목 
     - 선택항목에 이메일 주소와 닉네임은 가입 시 필수로 입력해야하는 항목인데요. `나. 선택항목`에서 해당 내용을 삭제해주세요. 
     - 선택항목에 '소속'을 추가해주세요. 
     - (거주지 정보, 소속) 수집 이용 목적도 알맞게 수정해주세요. 

--- 
(참고. 회원가입 시 입력 정보)

필수
- 이메일 주소
- 비밀번호
- 닉네임

선택
- 거주지 정보 (광역/ 시,군)
- 소속

**Comment by jay-parti** [comment]
위에 남겨주신 사항은 확인했는데요. 추가 확인 필요한 부분이 생겨서요. [문서](https://docs.google.com/document/d/1bu6PChwJfJB-kISMrbTkQCawx9tLPaHfILo151hDhTE/edit#heading=h.mj70x71i3m4q)에 안나님 할당했습니다. 

빠띠가 운영기관이 아니라 '개인정보의 제3자 제공에 관한 사항'을 수정해야 할 것 같은데요. 조항에 아예 없어진 것이 있더라구요. 확인해주시면 감사하겠습니다.   @anne-parti

**Comment by jay-parti** [comment]
개인정보처리방침, 서비스 이용약관 내용 업데이트했습니다. @anne-parti 

pdf로 외부에서도 볼 수 있는 링크 만들었는데요. 이렇게 전달드리면 될까요? 
 [서비스 이용약관](https://drive.google.com/file/d/1XptTrdZnOtUOP1Dc4SZVnaQ1xGtx5v3O/view?usp=sharing)
 [개인정보처리방침](https://drive.google.com/file/d/1AIU_8dBROEUrR_vyc629OhPQ_PdLRDcz/view?usp=sharing)

**Comment by anne-parti** [comment]
푸터, 회원가입 페이지에서 확인 완료했습니다.
