### ISSUE TITLE
[녹전연] 비밀번호 재설정 이메일 내용 수정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#91]
파이어베이스에서 비밀번호 재설정 이메일 수정 
- 제목
- 본문
- 링크 등

**Comment by anne-parti** [comment]
@jay-parti 
비밀번호 재설정 메일 제목과 내용을 수정했습니다. 
확인하시고 발신자 이름, 제목, 메일 본문 중 내용 수정이 필요한 부분이 있으시면 알려주세요. 
플랫폼 이름(녹색오리) 위주로 수정 및 추가가 필요한지 확인 부탁드립니다. 

### 발신자 
녹색오리 <noreply@green-newdeal.firebaseapp.com>

### 제목
[녹색오리] 비밀번호 재설정

### 본문
안녕하세요.

녹색오리 웹사이트의 비밀번호를 잊으셨나요?
아래 링크를 누르면 비밀번호 재설정 페이지로 이동합니다.

[비밀번호 재설정](url)

--
이메일 주소를 잘못 입력해 메일이 발송됐을 수 있습니다. 비밀번호 재설정을 요청하지 않으셨다면 이 이메일을 무시하세요.
이 메일은 발신전용으로 회신되지 않습니다.

<img width="667" alt="스크린샷 2021-01-29 오후 2 54 30" src="https://user-images.githubusercontent.com/55128558/106237527-5f3b0880-6242-11eb-9d96-2199f1243d06.png">

**Comment by jay-parti** [comment]
제가 보기에 수정사항은 없는 것 같은데요. 녹전연에 공유드리고, 수정의견 받아보겠습니다. @anne-parti

**Comment by jay-parti** [comment]
이메일 내용 수정 관련해서 별도 수정의견 없었습니다. @anne-parti
