### ISSUE TITLE
[녹전연] 게시판별 타입/ 입력필드/ 목록 뷰 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#92]
@jay-parti 
이 문서에 수정해주세요
1. 게시판 이름, 순서 조정이 필요하면 수정해주세요.
2. 목록 뷰는 게시판 타입이 '소식' 일 경우에만 작성해주세요.
3. 추가 입력 필드는 기본 입력 필드 외 추가되어야 하는 입력 필드가 있을 경우 적어주세요
    - 예. 주소(지도), 주제 선택, 지역 선택, 해시태그 등 

### 1. 공론장
- 타입: 제안게시판
- 목록 뷰: 
- 입력 필드: 주제 선택
최하단 '제안제출' --> '제안하기'로 수정

### 2. 모임
- 타입: 모임게시판
- 목록 뷰: 
- 입력 필드: 지도, 주제 선택, 해시태그

### 3. 도서관
- 타입: 소식게시판
- 목록 뷰: 모자이크 형식
![경기도 마을 캡쳐](https://user-images.githubusercontent.com/65703242/105677337-11b35880-5f2f-11eb-8644-811a62eb6109.JPG)
- 입력 필드: 지도, 주제선택, 해시태그

**Comment by jay-parti** [comment]
주제 선택은 주제, 지역 선택할 수 있게 하는 목록 (아래 예시 이미지)
![image](https://user-images.githubusercontent.com/65703242/105679428-c6e71000-5f31-11eb-8a25-edb39e4ee7bc.png)
해시태그는 제안 게시판 형식의 해시태그로 이해하면 될까요?

우선 위 설명처럼 이해하고 본문 수정했습니다.

**Comment by anne-parti** [comment]
@jay-parti 네네 맞습니다. 회의 후에 선정된 주제 공유 부탁드려요! 참고를 위해 서원님도 태그합니다. @iamswain25

**Comment by jay-parti** [comment]
'1. 공론장'에 문구 수정 요청사항 추가했습니다.

**Comment by jay-parti** [comment]
선정된 주제 공유드립니다. @anne-parti 

정의로운전환, 사회적경제, 순환경제, 기후운동, 탈성장, 코로나19, 지역분권, 에너지전환, 전환의방법론, 주거권

**Comment by anne-parti** [comment]
@jenna1k @iamswain25 주제 확인 후 작업 부탁드립니다.

**Comment by anne-parti** [comment]
@jay-parti 이 주제는 어느 게시판에 적용하면 되나요? 모든 게시판 입력 필드에 주제 선택이 있는데 3개 모두에 동일하게 적용하면 될까요?

**Comment by jay-parti** [comment]
@anne-parti 넵 모든 게시판에 동일하게 적용 부탁드립니다.

**Comment by anne-parti** [comment]
@jenna1k @iamswain25 모든 게시판 글 작성페이지에 아래 주제(태그) 선택 가능하도록 작업 부탁드립니다.

주제: 정의로운전환, 사회적경제, 순환경제, 기후운동, 탈성장, 코로나19, 지역분권, 에너지전환, 전환의방법론, 주거권
선택 형식: https://github.com/parti-coop/parti-mx-spa/issues/92#issuecomment-766639257

**Comment by jay-parti** [comment]
고정태그 목록 수정 요청이 왔습니다. 이렇게 빨리 수정요청하실줄 몰랐는데요. 다음주 테스트까지 반영이 가능할까요? @anne-parti 

에너지전환, 건물&주거, 교통, 순환경제&자원순환, 공원&생물다양성, 농업먹거리, 문화예술, 정의로운전환, 사회적경제, 어떻게_사회를_전환할_것인가

**Comment by iamswain25** [comment]
제안 게시판 (공론장)에 주소 필드가 빠져 있는데 저번에 @jay-parti 님이 모든 게시판 목록에서 지도로 볼 수 있게 해달라고 요청하셨거든요. @anne-parti 주소 필드 넣거나, 제안 게시판엔 지도보기 빼야할 것 같아요. 확인 필요합니다.

**Comment by iamswain25** [comment]
> 고정태그 목록 수정 요청이 왔습니다. 이렇게 빨리 수정요청하실줄 몰랐는데요. 다음주 테스트까지 반영이 가능할까요? @anne-parti
> 
> 에너지전환, 건물&주거, 교통, 순환경제&자원순환, 공원&생물다양성, 농업먹거리, 문화예술, 정의로운전환, 사회적경제, 어떻게_사회를_전환할_것인가

제가 바로 반영할게요

**Comment by anne-parti** [comment]
### 공론장 
게시판 타입: 제안

1. 글쓰기/ 수정 페이지 타이틀을 수정해주세요
    - 제안글쓰기 → `공론장 제안글 쓰기`
2. 제안 내용에 에디터 변환 체크박스를 추가하고 에디터로 변경 가능하도록 수정해주세요. 
3. 해시태그, 주소 입력필드를 추가해주세요. 
    - 해시태그
        - 입력 필드 플레이스 홀더를 수정해주세요 
        - Enter your hashtag → 단어 입력후 엔터를 눌러 추가하세요
    - 주소
        - https://github.com/parti-coop/parti-mx-spa/issues/92#issuecomment-776497971
        - 공론장 게시판에서 입력한 주소도 홈 > 지도에 핀으로 표시해주세요
4. 입력 필드 순서 변경이 가능하다면 변경 부탁드립니다
    1. 제목
    2. 제안 배경
    3. 제안 내용
    4. 주제 선택
    5. 해시태그
    6. 지도
    7. 제안 종료 방법
    8. 첨부 파일 영역
5. '주제 선택' 입력 필드 타이틀의 폰트 사이즈를 16px로 수정해주세요. 글쓰기 페이지 타이틀이랑 구분이 잘 안됩니다. 
5. attach images, attach files 버튼 명을 이미지 첨부, 파일 첨부로 수정해주세요
6. ‘제안 제출’ 버튼명을 ‘제출하기’로 변경해주세요 

---
### 모임
게시판 타입: 모임

1. 글쓰기/수정 페이지 타이틀을 수정해주세요
    - 모임 → `모임 새글 쓰기`
    - 모임 수정 → `모임 글 수정`
2. '모임 장소' 입력 필드가 누락되어 있습니다. 입력 필드를 추가해주세요. 현재 글 작성 시 하단 모임 정보에 모임 장소 (공란) 으로 표시됩니다.
    - 모임 장소 입력 필드의 레이블과 플레이스 홀더를 `모임 장소(또는 화상회의 링크)`로 수정해주세요.
        <img width="240" alt="스크린샷 2021-02-11 오전 12 02 52" src="https://user-images.githubusercontent.com/55128558/107527853-8f988480-6bfc-11eb-861d-d4d1cc7a57e5.png"> <img width="202" alt="스크린샷 2021-02-11 오전 12 02 44" src="https://user-images.githubusercontent.com/55128558/107527862-932c0b80-6bfc-11eb-9fcb-fcafb87a1a56.png">
    - 글 작성 완료 후 상세 페이지의 의 모임 정보 영역 기존과 동일하게 `모임 장소`로 유지해주세요. 
        <img width="158" alt="스크린샷 2021-02-11 오전 12 03 06" src="https://user-images.githubusercontent.com/55128558/107527915-a17a2780-6bfc-11eb-9e74-53306bd243a0.png">
3. 입력 필드 순서 변경이 가능하다면 변경 부탁드립니다
    1. 모임명
    2. 내용
    3. 일시
    4. 모임 장소
    5. 모집 인원
    6. 신청 마감일
    7. 주제 선택
    8. 해시태그
    9. 주소
    10. 첨부파일
4. '주제 선택' 입력 필드 타이틀의 폰트 사이즈를 16px로 수정해주세요. 글쓰기 페이지 타이틀이랑 구분이 잘 안됩니다. 
5. 해시태그 입력 필드 플레이스 홀더를 수정해주세요.
    - Enter your hashtag → 단어 입력후 엔터를 눌러 추가하세요
6. attach images, attach files 버튼 명을 이미지 첨부, 파일 첨부로 수정해주세요

--- 
### 도서관
게시판 타입: 소식

1. 글쓰기/수정 페이지 타이틀을 수정해주세요
    - 소식 쓰기 → `도서관 새글 쓰기`
    - 소식 수정 → `도서관 글 수정`
2. '주제 선택' 입력 필드 타이틀의 폰트 사이즈를 16px로 수정해주세요. 글쓰기 페이지 타이틀이랑 구분이 잘 안됩니다. 
3. 해시태그 입력 필드 플레이스 홀더를 수정해주세요.
    - Enter your hashtag → 단어 입력후 엔터를 눌러 추가하세요
4. attach images, attach files 버튼 명을 이미지 첨부, 파일 첨부로 수정해주세요

**Comment by jay-parti** [comment]
게시판별 입력필드 필수/선택 입력사항 전달드립니다. @anne-parti 

**공론장**
- 제목 / 제안 배경 / 제안 종료 방법 / 제안 내용 : 필수
- 주제 선택 / 해시태그 : 선택
- 주소 : 선택

**모임**
- 모임명 / 일시 / 모집인원 / 신청마감일 / 내용 : 필수
- 주제 선택 / 해시태그 : 선택 (*공론장과 동일)
- 화상회의 링크 / 주소 : 선택

**도서관**
- 제목 / 내용 : 필수
- 주제 선택 / 해시태그 : 선택 (*공론장과 동일)
- 주소 : 선택


**문의**
**공론장** 
- 주제 선택과 해시태그 둘 중 하나를 필수가 가능할지 문의주셨습니다. 혹시 어렵다면 두 가지 모두 선택사항으로 하면 좋을 것 같다고 하셨는데요. / _주제선택을 필수로 하고, 고정태그에 '기타'를 추가하면 어떨까 싶습니다._ 
- 해시태그 입력 전 보이는 문구를 다음과 같이 수정 요청주셨습니다. 모바일로 봤을 때 텍스트가 길지 않을까 싶긴한데 가능할까요? 
![image](https://user-images.githubusercontent.com/65703242/107907355-d7216680-6f96-11eb-8e42-4ec6f992412c.png)
_제안하고자 하는 내용의 주제를 기존 태그에서 선택할 수 없을 경우 추가해 주세요(단어 입력후 엔터를 눌러 추가하세요)_
 

**모임**  
- 워딩은 ‘화상회의 링크'로 요청주셨습니다. 
- 화상회의 링크와 주소의 경우에도 둘 중 하나 필수가 가능할까요? 안된다면 두 개 다 선택으로 남기면 좋을 것 같습니다.

**Comment by jay-parti** [comment]
(게시판 공통) 주소 입력 필드에 기존 '주소를 검색하세요'에서 “**주소 입력 시 게시판 지도에 위치정보가 표시됩니다.**” 로 수정 요청드립니다. @anne-parti 
![image](https://user-images.githubusercontent.com/65703242/107919383-903f6b00-6fae-11eb-8b26-cce1e0aa1c2c.png)

**Comment by anne-parti** [comment]
@jenna1k 수정 내용 확인했습니다.
@jay-parti 말씀하신 내용은 새로운 이슈 등록해서 다시 코멘트 달아둘게요.
