### ISSUE TITLE
[녹전연] 사이트 타이틀, 키컬러, 푸터. 공유메시지 전달 

### ISSUE THREAD

**Issue by jay-parti** [parti-coop/parti-mx-spa#93]
1. 사이트 타이틀
- 녹색전환을 위한 지역 그린뉴딜 플랫폼 녹색오리
- 녹색전환을 위한 지역 그린뉴딜 플랫폼는 ‘녹색오리'에 비해 작고 연한 글씨로 표시

2. 키컬러
- 1st  #008083 / 2nd #01babd / 3rd #f7a17e / 4th #aed9bb
<img width="835" alt="컬러_녹전연" src="https://user-images.githubusercontent.com/65703242/105648583-97afaf00-5eef-11eb-9375-268a6d995b9b.png">

3. 푸터
- 녹색전환연구소 Institute for Green Transformation
- 서울시 종로구 자하문로 17길 12-9, 2층(03035) 
- 전화 : 070-4820-4900/4998 
- Fax: (표기하지 않음)
- mail2igt@daum.net 

4. 공유메시지
- (제목) 지역 그린뉴딜 플랫폼 ‘녹색오리’
- (내용) 녹색전환을 위한 지역 그린뉴딜 플랫폼입니다

**Comment by jay-parti** [comment]
1/26 미팅 후 사이트 타이틀을 기존보다 길게 요청주셨는데요. 
텍스트 배치나 '작고 연한 글씨'에 대해 녹전연에 더 요청을 드려야할까요? @anne-parti

**Comment by iamswain25** [comment]
https://material-ui.com/customization/default-theme/#default-theme 키 칼러는 저희가 메테리얼 테마의 primary main만 현재 쓰고 있습니다. 그래서 첫번째 칼라만 적용이 가능합니다. 나머지 칼라도 적용하려면 디자인에서 검토가 필요합니다.

**Comment by anne-parti** [comment]
@jay-parti 사이트 상단 이미지 영역 말씀하시는 것이라면 이미지를 수정하시면 됩니다. 타이틀 이미지를 저희가 제작하나요?

**Comment by jay-parti** [comment]
이번에 디자인 과업은 없는데요. 사이트 타이틀에 들어가는 내용 (아래 이미지에 예시 표시)도 이미지일까요? 

![image](https://user-images.githubusercontent.com/65703242/106098179-f4bf9500-617b-11eb-9006-8a0fd6f05d0f.png)

**Comment by anne-parti** [comment]
@jay-parti 네네 이미지 파일입니다 녹전연 구현된 사이트 가보시면 이미지 파일로 되어 있어요. 최초에 녹전연에서 전달받은거라면 녹전연에서 수정해서 주셔야 할 것 같습니다~!

**Comment by jenna1k** [comment]
지금 로고 이미지는 제가 임의로 녹전연 사이트에서 가져왔습니다. 
배너이미지도 임의로 넣었구요, 그룹정보 수정 페이지에서 관리자가 데스크탑/모바일 배너 이미지 업로드하시고 타이틀 텍스트 변경도 가능합니다
타이틀이미지 없이 텍스트로 대체하면 아래와 같이 보입니다.
![image](https://user-images.githubusercontent.com/20438637/106101025-a52f9800-6180-11eb-9789-4417bce0d335.png)

**Comment by jay-parti** [comment]
@jenna1k 관리자가 타이틀 변경하면 해당 텍스트에 색을 입히거나 파비콘 넣는 작업은 불가능할까요?
불가능하다면 이미지 만드시라고 요청 드려야 할 것 같습니다.

**Comment by jenna1k** [comment]
@jay-parti  텍스트에 색을 넣거나 로고 업로드는 현재 불가능합니다. 
로고 이미지 크기는 상관없으나 비율은 지금 로고와 비슷하면 괜찮을것 같습니다 (1:4비율)
![image](https://user-images.githubusercontent.com/20438637/106103931-09545b00-6185-11eb-8cb0-725fda2efed2.png)

**Comment by jay-parti** [comment]
확인했습니다. 녹전연에 이미지 요청드리겠습니다.

**Comment by jay-parti** [comment]
사이트 타이틀 이미지 전달드립니다. @anne-parti 
https://drive.google.com/file/d/1tOPRnF1j6fc7M8OnuKtgZLmyuBd7WCDw/view?usp=sharing

**Comment by jay-parti** [comment]
푸터기입 이메일 변경요청이 왔습니다. 반영요청드려요. @anne-parti 

기존 : mail2igt@daum.net
요청 : igt.greenduck@gmail.com

**Comment by iamswain25** [comment]
> 푸터기입 이메일 변경요청이 왔습니다. 반영요청드려요. @anne-parti
> 
> 기존 : [mail2igt@daum.net](mailto:mail2igt@daum.net)
> 요청 : [igt.greenduck@gmail.com](mailto:igt.greenduck@gmail.com)

제가 처리할게요

**Comment by anne-parti** [comment]
1. 사이트 타이틀 영역에 공유 메시지 제목과 동일하게 들어가있는데요. 사이트 타이틀 영역(스크린샷 참고)에 들어갈 메시지를 다시 한 번 확인 부탁드립니다. @jay-parti 
    - <img width="412" alt="스크린샷 2021-02-10 오후 4 11 24" src="https://user-images.githubusercontent.com/55128558/107477289-d49bc700-6bba-11eb-98bf-62664678f8b5.png">
    - 현재: 지역 그린뉴딜 플랫폼 ‘녹색오리’

2. https://green-newdeal.web.app/ 공유해주신 이미지(녹색오리_og 이미지.png)로 사이트 타이틀 PC/ 모바일, 공유 이미지 모두 사용하는게 맞나요? 사이트 타이틀은 모바일, PC 최적 이미지 사이즈(비율)가 다르기 때문에 PC 버전에서 아름답지 않게 나옵니다.. PC 사이즈에 최적화된 이미지가 필요합니다. @jay-parti 
    - PC (1140 X 260)
    - 모바일 (360 X 180)

2. 전화번호 부분 띄어쓰기를 수정해주세요 @jenna1k 
    - AS-IS: 070-4820-4900 /070-4820-4998
    - TO-BE: 070-4820-4900 / 070-4820-4998

**Comment by jay-parti** [comment]
1,2번 녹전연에 확인, 요청하겠습니다.
2번에서 사이트 타이틀은 [녹색오리_site title](https://drive.google.com/file/d/1tOPRnF1j6fc7M8OnuKtgZLmyuBd7WCDw/view?usp=sharing), [녹색오리_og 이미지](https://drive.google.com/file/d/1x3iYD7tYJRoHkcjaudoi3caQe-5N27-k/view?usp=sharing)입니다. 

사이트 타이틀 이미지도 모바일, pc버전이 필요하군요. 지금은 모바일에 적합한 사이즈 맞을까요? 그러면 모바일용으로 녹전연에 요청드리겠습니다. @anne-parti

**Comment by jenna1k** [comment]
> 사이트 타이틀 이미지도 모바일, pc버전이 필요하군요. 지금은 모바일에 적합한 사이즈 맞을까요? 그러면 모바일용으로 녹전연에 요청드리겠습니다. @anne-parti

녹색오리_og 이미지 PC용 (1140 X 260)을 요청 부탁드려요
현재는 모바일로 볼 경우 이미지 전체가 다 보이고, PC로 볼 경우 이미지 상하단이 잘려보입니다
- PC화면:
![image](https://user-images.githubusercontent.com/20438637/107482746-758e8000-6bc3-11eb-91fa-eb978f3979e9.png)

**Comment by jay-parti** [comment]
제나님 말씀주신 부분은 커버 디자인으로 알고 있는데요. 해당 이미지는 아직 녹전연에서 디자인 중입니다. 커버는 운영자가 직접 입힐 수 있는 걸로 알고 있어서 디자인 되는대로 보내달라고 말씀드렸습니다. @jenna1k 
![image](https://user-images.githubusercontent.com/65703242/107485185-c9e72f00-6bc6-11eb-8172-1a38f3d3b18a.png)

**Comment by jay-parti** [comment]
> 1,2번 녹전연에 확인, 요청하겠습니다.
> 2번에서 사이트 타이틀은 [녹색오리_site title](https://drive.google.com/file/d/1tOPRnF1j6fc7M8OnuKtgZLmyuBd7WCDw/view?usp=sharing), [녹색오리_og 이미지](https://drive.google.com/file/d/1x3iYD7tYJRoHkcjaudoi3caQe-5N27-k/view?usp=sharing)입니다.
> 
> 사이트 타이틀 이미지도 모바일, pc버전이 필요하군요. 지금은 모바일에 적합한 사이즈 맞을까요? 그러면 모바일용으로 녹전연에 요청드리겠습니다. @anne-parti

1번은 녹색전환 플랫폼 '녹색오리' 로 요청드립니다. @anne-parti

**Comment by anne-parti** [comment]
@jenna1k 
제나님 사이트 타이틀 변경 부탁드립니다 (참고 https://github.com/parti-coop/parti-mx-spa/issues/93#issuecomment-776503689)
> 1번은 `녹색전환 플랫폼 '녹색오리'`로 요청드립니다. @anne-parti

**Comment by anne-parti** [comment]
사이트 타이틀 확인했습니다. PC 버전 메인이미지 변경은 따로 이슈로 올려둘게요.

**Comment by jay-parti** [comment]
모바일 기준으로 홈에서 햄버거 버튼 클릭하면 사이트 타이틀 이미지가 이렇네 나오는데요. 비율이 어색해보이네요.
 모바일용 사이트 타이틀 이미지를 녹전연에 요청드려야할까요? 위 논의에 있었는데 제가 놓쳤을 수도 있을 것 같습니다. @anne-parti 
![image](https://user-images.githubusercontent.com/65703242/108163232-facce400-7131-11eb-9ad1-c9bad97d96dd.png)

**Comment by anne-parti** [comment]
@jenna1k 
1. 위 이슈 확인 부타드려요. 
2. 모바일에 햄버거 메뉴 > 로그인 접속 시 우측 상단에 닫기 버튼이 제거되지 않은채 남아 있어서 레이아웃이 깨집니다. 모바일 회원가입 페이지와 동일하게 수정 부탁드립니다.

**Comment by anne-parti** [comment]
@jenna1k 2번 이슈 테스트해보았는데 동일하게 나오는데 다시 한 번 확인 부탁드립니다 🙇‍♀️

<img width="301" alt="스크린샷 2021-02-19 오전 10 46 34" src="https://user-images.githubusercontent.com/55128558/108445524-e3ac0480-729f-11eb-8380-9bcb0f5daaaa.png"> → <img width="306" alt="스크린샷 2021-02-19 오전 10 46 42" src="https://user-images.githubusercontent.com/55128558/108445529-e575c800-729f-11eb-86c1-67ed9f57cb0e.png">


> 
> 1. 위 이슈 확인 부타드려요.
> 2. 모바일에 햄버거 메뉴 > 로그인 접속 시 우측 상단에 닫기 버튼이 제거되지 않은채 남아 있어서 레이아웃이 깨집니다. 모바일 회원가입 페이지와 동일하게 수정 부탁드립니다.

**Comment by jenna1k** [comment]
@anne-parti 죄송합니다 수정했습니다!

**Comment by anne-parti** [comment]
확인 완료했습니다. 감사합니다~
