### ISSUE TITLE
[녹전연] 게시판 타입 제안, 투표, 모임 기간 종료된 후에도 관리자 수정 가능하도록 변경

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#94]
일부 게시판 타입이 게시글이 기간 종료 후에는 수정, 삭제가 불가능하도록 되어 있는데 관리자 계정에서는 수정, 삭제 가능하도록 변경 필요.
(수정 시 별도 수정 이력이 남지 않으므로 관리자가 수정했다는 코멘트 남기도록 안내 부탁드립니다. )

**Comment by iamswain25** [comment]
관리자가 직접 본문에 적을 수 있도록 안내해야 할 것 같아요. 프로그램으로 지정 시 디자인 필요합니다.

**Comment by anne-parti** [comment]
@iamswain25 네 저번 회의 때 제이님께도 말씀 드렸습니다. 
@jay-parti 제이님 추후에 투표, 제안, 모임 등 종료 후 본문 수정(결과 정리 추가) 시) 작성자가 추가 내용과 함께 언제/무슨 이유로 수정했다는 코멘트를 남기도록 안내 부탁드려요.

**Comment by jay-parti** [comment]
넵 녹전연에 안내드리겠습니다.

**Comment by anne-parti** [comment]
@jay-parti 님 이 이슈는 클로즈해도 될까요?

**Comment by jay-parti** [comment]
네네 클로즈해도 될 것 같습니다. 감사해요 @anne-parti
