### ISSUE TITLE
[녹전연] 검색 결과 페이지 개선

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#95]
1. 검색 결과에 게시글+게시판 이름 함께 표시 
2. (가능하다면) 검색 결과 게시판별로 묶어서 표시

**Comment by jenna1k** [comment]
06be1cd0cbeff7b0d1561d2c730b265b66b9f369
243299479f7917c03f73f68511976fcd875f66d0

**Comment by anne-parti** [comment]
@jenna1k 새벽에 작업해서 글 등록 안하고 창을 꺼버렸나봐요 😅
1. 검색어 입력폼에 Search here.. 을 `검색어를 입력하세요`로 변경해주세요
2. 검색어 타이틀 과 검색결과 수 사이에 띄어쓰기를 추가해주세요.
    <img width="170" alt="스크린샷 2021-02-11 오전 1 10 39" src="https://user-images.githubusercontent.com/55128558/107917479-5751c700-6fab-11eb-87c1-683eb03f0ceb.png">

**Comment by anne-parti** [comment]
확인 완료했습니다. 감사합니다~!
